export type SchemaType =
  | 'messari-dex'
  | 'messari-lending'
  | 'messari-rwa'
  | 'messari-staking'
  | 'messari-yield'
  | 'messari-bridge'
  | 'messari-perp'
  | 'uniswap-v2'
  | 'uniswap-v3'
  | 'algebra-v1'
  | 'etherfi-native'
  | 'polymarket';

export type ProtocolCategory =
  | 'DEX'
  | 'Lending'
  | 'Liquid Staking'
  | 'Yield Aggregator'
  | 'Prediction Markets'
  | 'Bridge'
  | 'RWA'
  | 'Perpetuals';

export interface ProtocolConfig {
  slug: string;
  name: string;
  category: ProtocolCategory;
  description: string;
  subgraphId: string;
  schemaType: SchemaType;
  website: string;
  chains: string[];
  color: string;
  /** Known upstream data quality issue — surfaced as a notice on the detail page. */
  knownIssues?: string;
  /** Which 90-day chart the knownIssues message belongs to. Defaults to 'fees'. */
  knownIssueAffects?: 'fees' | 'volume';
}

export const PROTOCOLS: ProtocolConfig[] = [
  {
    slug: 'uniswap-v3',
    name: 'Uniswap V3',
    category: 'DEX',
    description: 'The leading decentralised exchange on Ethereum, enabling permissionless token swaps with concentrated liquidity positions.',
    subgraphId: '5zvR82QoaXYFyDEKLZ9t6v9adgnptxYpKpSbxtgVENFV',
    schemaType: 'uniswap-v3',
    website: 'https://uniswap.org',
    chains: ['Ethereum'],
    color: '#FF007A',
  },
  {
    slug: 'uniswap-v2',
    name: 'Uniswap V2',
    category: 'DEX',
    description: 'The original constant-product AMM that proved permissionless token swaps at scale on Ethereum. Flat 0.30% fee, still the deepest liquidity venue for many long-tail ERC-20 pairs.',
    subgraphId: 'GmSczqdCDZ3hJeYY9JphwsADn5rePUzUKm8EZcVuhRAm',
    schemaType: 'uniswap-v2',
    website: 'https://uniswap.org',
    chains: ['Ethereum'],
    color: '#FF6699',
  },
  {
    slug: 'uniswap-v3-polygon',
    name: 'Uniswap V3 (Polygon)',
    category: 'DEX',
    description: 'Uniswap V3 deployment on Polygon. Established L2 venue with deep MATIC and stablecoin liquidity, queried via the same v3 schema as the mainnet deployment.',
    subgraphId: '3hCPRGf4z88VC5rsBKU5AA9FBBq5nF3jbKJG7VZCbhjm',
    schemaType: 'uniswap-v3',
    website: 'https://app.uniswap.org',
    chains: ['Polygon'],
    color: '#8247E5',
  },
  {
    slug: 'aave-v3',
    name: 'Aave V3',
    category: 'Lending',
    description: 'Decentralised non-custodial liquidity protocol where users supply assets to earn yield and borrow against collateral. This dashboard tracks the Ethereum mainnet deployment.',
    subgraphId: 'JCNWRypm7FYwV8fx5HhzZPSFaMxgkPuw4TnR3Gpi81zk',
    schemaType: 'messari-lending',
    website: 'https://aave.com',
    chains: ['Ethereum'],
    color: '#B6509E',
  },
  {
    slug: 'aave-v3-arbitrum',
    name: 'Aave V3 (Arbitrum)',
    category: 'Lending',
    description: 'Aave V3 on Arbitrum One. Major L2 lending venue with deep ARB ecosystem assets, separate liquidity from the Ethereum deployment.',
    subgraphId: '4xyasjQeREe7PxnF6wVdobZvCw5mhoHZq3T7guRpuNPf',
    schemaType: 'messari-lending',
    website: 'https://app.aave.com',
    chains: ['Arbitrum'],
    color: '#28A0F0',
  },
  {
    slug: 'aave-v3-polygon',
    name: 'Aave V3 (Polygon)',
    category: 'Lending',
    description: 'Aave V3 on Polygon PoS. Long-running L2 deployment with deep MATIC/USDC/USDT/DAI markets, separate liquidity pool from the Ethereum and Arbitrum deployments.',
    subgraphId: '6yuf1C49aWEscgk5n9D1DekeG1BCk5Z9imJYJT3sVmAT',
    schemaType: 'messari-lending',
    website: 'https://app.aave.com',
    chains: ['Polygon'],
    color: '#8247E5',
  },
  {
    slug: 'aave-v3-avalanche',
    name: 'Aave V3 (Avalanche)',
    category: 'Lending',
    description: 'Aave V3 on Avalanche C-Chain. Native AVAX, USDC, USDT, BTC.b, and ETH.e money markets, the dominant lending venue on Avalanche by TVL alongside BENQI.',
    subgraphId: '72Cez54APnySAn6h8MswzYkwaL9KjvuuKnKArnPJ8yxb',
    schemaType: 'messari-lending',
    website: 'https://app.aave.com',
    chains: ['Avalanche'],
    color: '#E84142',
  },
  {
    slug: 'aave-v2-ethereum',
    name: 'Aave V2 (Ethereum)',
    category: 'Lending',
    description: 'Legacy Aave V2 deployment on Ethereum mainnet. Mostly drained as users migrated to V3, with residual liquidity remaining in long-tail markets that V3 never re-listed.',
    subgraphId: 'C2zniPn45RnLDGzVeGZCx2Sw3GXrbc9gL4ZfL8B8Em2j',
    schemaType: 'messari-lending',
    website: 'https://app.aave.com/?marketName=proto_mainnet',
    chains: ['Ethereum'],
    color: '#7E5DCF',
  },
  {
    slug: 'aave-v2-polygon',
    name: 'Aave V2 (Polygon)',
    category: 'Lending',
    description: 'Legacy Aave V2 on Polygon. Same long-tail residual story as the Ethereum V2 deployment, kept around for users who never migrated their positions.',
    subgraphId: 'GrZQJ7sWdTqiNUD8Vh2THaeBM4wGwiF8mFv9FBfyzwxm',
    schemaType: 'messari-lending',
    website: 'https://app.aave.com/?marketName=proto_polygon',
    chains: ['Polygon'],
    color: '#9C7FE0',
  },
  {
    slug: 'aave-v3-gnosis',
    name: 'Aave V3 (Gnosis)',
    category: 'Lending',
    description: 'Aave V3 on Gnosis Chain. The dominant lending market on Gnosis, with concentrated liquidity around xDAI and wstETH. Sister deployment to the Spark fork that operates on the same chain.',
    subgraphId: 'GiNMLDxT1Bdn2dQZxjQLmW24uwpc3geKUBW8RP6oEdg',
    schemaType: 'messari-lending',
    website: 'https://app.aave.com',
    chains: ['Gnosis'],
    color: '#04795B',
  },
  {
    slug: 'compound-v3',
    name: 'Compound V3',
    category: 'Lending',
    description: 'Open-source interest rate protocol allowing users to supply collateral and borrow the base asset.',
    subgraphId: 'AwoxEZbiWLvv6e3QdvdMZw4WDURdGbvPfHmZRc8Dpfz9',
    schemaType: 'messari-lending',
    website: 'https://compound.finance',
    chains: ['Ethereum'],
    color: '#00D395',
  },
  {
    slug: 'compound-v3-arbitrum',
    name: 'Compound V3 (Arbitrum)',
    category: 'Lending',
    description: 'Compound V3 on Arbitrum One. Single-base-asset money markets with USDC and ETH borrowing; one of the busier Compound deployments outside of mainnet.',
    subgraphId: '5MjRndNWGhqvNX7chUYLQDnvEgc8DaH8eisEkcJt71SR',
    schemaType: 'messari-lending',
    website: 'https://compound.finance',
    chains: ['Arbitrum'],
    color: '#28A0F0',
  },
  {
    slug: 'compound-v3-polygon',
    name: 'Compound V3 (Polygon)',
    category: 'Lending',
    description: 'Compound V3 on Polygon PoS. Smaller deployment than Arbitrum, anchored around USDC borrowing against blue-chip collateral.',
    subgraphId: '5wfoWBpfYv59b99wDxJmyFiKBu9brXESeqJAzw8WP5Cz',
    schemaType: 'messari-lending',
    website: 'https://compound.finance',
    chains: ['Polygon'],
    color: '#8247E5',
  },
  {
    slug: 'makerdao',
    name: 'MakerDAO',
    category: 'Lending',
    description: 'Decentralised CDP-based lending protocol behind DAI, the longest-running on-chain stablecoin issuance system. Users lock collateral to mint DAI against it.',
    subgraphId: '8sE6rTNkPhzZXZC6c8UQy2ghFTu5PPdGauwUBm4t7HZ1',
    schemaType: 'messari-lending',
    website: 'https://makerdao.com',
    chains: ['Ethereum'],
    color: '#1AAB9B',
  },
  {
    slug: 'morpho-blue',
    name: 'Morpho Blue',
    category: 'Lending',
    description: 'Permissionless lending primitive: each market is a single isolated pair of collateral and loan assets, with risk parameters set by curators rather than governance.',
    subgraphId: '8Lz789DP5VKLXumTMTgygjU2xtuzx8AhbaacgN5PYCAs',
    schemaType: 'messari-lending',
    website: 'https://morpho.org',
    chains: ['Ethereum'],
    color: '#2470FF',
    knownIssues: 'The upstream subgraph writes $0 to dailyProtocolSideRevenueUSD across all snapshots despite a non-zero cumulative figure. Daily fee charts show no data until this is fixed upstream.',
  },
  {
    slug: 'spark-lend',
    name: 'Spark Lend',
    category: 'Lending',
    description: 'Aave V3 fork operated by the Sky / MakerDAO ecosystem on Ethereum mainnet, with sDAI yield routing baked into the supply side. The largest Spark deployment by TVL.',
    subgraphId: 'GbKdmBe4ycCYCQLQSjqGg6UHYoYfbyJyq5WrG35pv1si',
    schemaType: 'messari-lending',
    website: 'https://spark.fi',
    chains: ['Ethereum'],
    color: '#E07A52',
  },
  {
    slug: 'spark-lend-gnosis',
    name: 'Spark Lend (Gnosis)',
    category: 'Lending',
    description: 'Spark Lend on Gnosis Chain, the Aave V3 fork operated by the Sky / MakerDAO ecosystem and integrated with sDAI yield routing.',
    subgraphId: 'Bw4RH37UbbGEhHo4FaWwT1dn9QJzm1XSZCyK1cbr6ZKM',
    schemaType: 'messari-lending',
    website: 'https://spark.fi',
    chains: ['Gnosis'],
    color: '#F58A65',
    knownIssues: 'The upstream subgraph writes $0 to dailyBorrowUSD across all snapshots while the cumulative borrow figure remains correct. Daily borrowing chart shows no data until this is fixed upstream.',
    knownIssueAffects: 'volume',
  },
  {
    slug: 'compound-v2',
    name: 'Compound V2',
    category: 'Lending',
    description: 'The original cToken-based money market on Ethereum. Pioneered algorithmic interest rates and remains a deep-liquidity venue for ETH, USDC, USDT, and DAI lending.',
    subgraphId: '4TbqVA8p2DoBd5qDbPMwmDZv3CsJjWtxo8nVSqF2tA9a',
    schemaType: 'messari-lending',
    website: 'https://app.compound.finance/markets/v2',
    chains: ['Ethereum'],
    color: '#00D395',
  },
  {
    slug: 'abracadabra',
    name: 'Abracadabra Money',
    category: 'Lending',
    description: 'Collateralised debt protocol issuing the MIM stablecoin against interest-bearing collateral (yvDAI, sUSD, lp tokens, etc.). Launched the early "magic internet money" framing in DeFi.',
    subgraphId: 'GLAu42kvVs7ixfXcmkAsRiS7Xt1NCpgkKsnz3qiriuvV',
    schemaType: 'messari-lending',
    website: 'https://abracadabra.money',
    chains: ['Ethereum'],
    color: '#FF55B6',
  },
  {
    slug: 'benqi',
    name: 'BENQI',
    category: 'Lending',
    description: 'Largest lending protocol native to Avalanche, plus liquid AVAX staking via sAVAX. Compound-style market design with AVAX, USDC, USDT, BTC.b, and ETH.e supply markets.',
    subgraphId: '8ZjJGsaKea7WwLJPJNdHXPGsvXDe3iq2231aRjgBPisi',
    schemaType: 'messari-lending',
    website: 'https://benqi.fi',
    chains: ['Avalanche'],
    color: '#FF1B6B',
  },
  {
    slug: 'inverse-finance',
    name: 'Inverse Finance',
    category: 'Lending',
    description: 'Issuer of DOLA, a debt-backed stablecoin, paired with the DBR fixed-rate borrowing right token. Borrowers stream DBR over time to hold open DOLA debt, decoupling the cost of credit from spot utilization-curve volatility.',
    subgraphId: 'EXuutY6qkZbXjYeJZdiDBf2imJswTNdfm8YZCqhAthfW',
    schemaType: 'messari-lending',
    website: 'https://inverse.finance',
    chains: ['Ethereum'],
    color: '#00C2A8',
  },
  {
    slug: 'lido',
    name: 'Lido',
    category: 'Liquid Staking',
    description: 'Largest liquid staking protocol on Ethereum, issuing stETH against pooled validator stake and dominating the LST market.',
    subgraphId: 'F7qb71hWab6SuRL5sf6LQLTpNahmqMsBnnweYHzLGUyG',
    schemaType: 'messari-staking',
    website: 'https://lido.fi',
    chains: ['Ethereum'],
    color: '#00A3FF',
  },
  {
    slug: 'rocket-pool',
    name: 'Rocket Pool',
    category: 'Liquid Staking',
    description: 'Permissionless liquid staking protocol issuing rETH. Lets stakers run their own validator nodes with as little as 8 ETH (alongside RPL collateral) and earn fee revenue from staked-on-behalf-of pool capital, the second-largest LST after Lido.',
    subgraphId: 'Dtj2HicXKpoUjNB7ffdBkMwt3L9Sz3cbENd67AdHu6Vb',
    schemaType: 'messari-staking',
    website: 'https://rocketpool.net',
    chains: ['Ethereum'],
    color: '#FF8852',
  },
  {
    slug: 'aerodrome',
    name: 'Aerodrome',
    category: 'DEX',
    description: 'Largest DEX on Base by TVL and volume. ve(3,3) AMM combining stable, volatile, and concentrated-liquidity (Slipstream) pools, with veAERO emissions directing liquidity.',
    subgraphId: 'GENunSHWLBXm59mBSgPzQ8metBEp9YDfdqwFr91Av1UM',
    schemaType: 'uniswap-v3',
    website: 'https://aerodrome.finance',
    chains: ['Base'],
    color: '#1A33FF',
  },
  {
    slug: 'pancakeswap-v3',
    name: 'PancakeSwap V3',
    category: 'DEX',
    description: 'Largest DEX on BNB Chain, with V3 also deployed to Ethereum. Concentrated-liquidity AMM forked from Uniswap V3 with multi-tier fees. This entry tracks the Ethereum mainnet deployment.',
    subgraphId: 'JAGXF8B14mpB8QGKnwhKTs5JxsQZBJQvbDGFcWwL7gbm',
    schemaType: 'messari-dex',
    website: 'https://pancakeswap.finance',
    chains: ['Ethereum'],
    color: '#D1884F',
  },
  {
    slug: 'uniswap-v3-arbitrum',
    name: 'Uniswap V3 (Arbitrum)',
    category: 'DEX',
    description: 'Uniswap V3 deployment on Arbitrum One. Major L2 venue with deep ARB-ecosystem liquidity, queried via the Messari DEX-AMM schema.',
    subgraphId: 'FQ6JYszEKApsBpAmiHesRsd9Ygc6mzmpNRANeVQFYoVX',
    schemaType: 'messari-dex',
    website: 'https://app.uniswap.org',
    chains: ['Arbitrum'],
    color: '#FF007A',
  },
  {
    slug: 'uniswap-v3-optimism',
    name: 'Uniswap V3 (Optimism)',
    category: 'DEX',
    description: 'Uniswap V3 deployment on Optimism. OP-ecosystem trading hub, queried via the Messari DEX-AMM schema.',
    subgraphId: 'EgnS9YE1avupkvCNj9fHnJxppfEmNNywYJtghqiu2pd9',
    schemaType: 'messari-dex',
    website: 'https://app.uniswap.org',
    chains: ['Optimism'],
    color: '#FF66B3',
  },
  {
    slug: 'velodrome-v2',
    name: 'Velodrome V2',
    category: 'DEX',
    description: 'Flagship native DEX on Optimism. ve(3,3) AMM with stable and volatile pools and veVELO emissions; the protocol Aerodrome was forked from before launching on Base.',
    subgraphId: 'A4Y1A82YhSLTn998BVVELC8eWzhi992k4ZitByvssxqA',
    schemaType: 'messari-dex',
    website: 'https://velodrome.finance',
    chains: ['Optimism'],
    color: '#FF1B6B',
  },
  {
    slug: 'camelot-v3',
    name: 'Camelot V3',
    category: 'DEX',
    description: 'Native Arbitrum DEX with concentrated-liquidity pools built on the Algebra V1 engine, plus dynamic fees and a launchpad pipeline. The most-used non-Uniswap DEX on Arbitrum.',
    subgraphId: '3utanEBA9nqMjPnuQP1vMCCys6enSM3EawBpKTVwnUw2',
    schemaType: 'algebra-v1',
    website: 'https://app.camelot.exchange',
    chains: ['Arbitrum'],
    color: '#E8B964',
  },
  {
    slug: 'ether-fi',
    name: 'ether.fi',
    category: 'Liquid Staking',
    description: 'Liquid restaking protocol on Ethereum issuing eETH (rebasing) and weETH (wrapped). Stakers earn validator rewards plus EigenLayer restaking yield. Largest LRT by TVL.',
    subgraphId: 'AEsX7AeqTD9bpFFaHwmCZbEXaHWsmzekoPKKuJUGQiQA',
    schemaType: 'etherfi-native',
    website: 'https://ether.fi',
    chains: ['Ethereum'],
    color: '#A0FFE6',
  },
  {
    slug: 'yearn-v2',
    name: 'Yearn V2',
    category: 'Yield Aggregator',
    description: 'Long-running yield optimisation protocol that routes deposits across vault strategies to maximise returns. The Ethereum mainnet V2 deployment, original automated yield primitive in DeFi.',
    subgraphId: 'FDLuaz69DbMADuBjJDEcLnTuPnjhZqNbFVrkNiBLGkEg',
    schemaType: 'messari-yield',
    website: 'https://yearn.fi',
    chains: ['Ethereum'],
    color: '#0657F9',
  },
  {
    slug: 'badger-dao',
    name: 'Badger DAO',
    category: 'Yield Aggregator',
    description: 'Bitcoin-on-Ethereum yield protocol. Sett vaults route wBTC, renBTC, and tBTC LP positions through automated strategies (Curve, Convex, Balancer) to compound yield while keeping exposure denominated in BTC.',
    subgraphId: 'BchjnXAXXV5coiCBMQH4A8yCHXEFX9S88JFF6G3mfem4',
    schemaType: 'messari-yield',
    website: 'https://badger.com',
    chains: ['Ethereum'],
    color: '#F2A52B',
  },
  {
    slug: 'goldfinch',
    name: 'Goldfinch',
    category: 'RWA',
    description: 'Uncollateralised credit pools backing real-world borrowers, primarily emerging-market fintechs. Liquidity providers fund Senior and Junior pools that finance off-chain credit deals; backers underwrite Borrower Pools and absorb first-loss tranches. Currently in harvest mode, no new originations in 90+ days but $105M of outstanding loans accruing interest daily.',
    subgraphId: 'GRwpFCPYyQPdz84sCnKemzrNvgFPuKkFLcRLR6jsRxHr',
    schemaType: 'messari-rwa',
    website: 'https://goldfinch.finance',
    chains: ['Ethereum'],
    color: '#FFCC55',
  },
  {
    slug: 'truefi',
    name: 'TrueFi',
    category: 'RWA',
    description: 'Uncollateralised institutional lending protocol. Capital pools fund credit lines to vetted borrowers (asset managers, market makers, crypto-native firms) on fixed terms. Originated $1.7B+ in lifetime credit and earned $41M+ in revenue with zero defaults to date.',
    subgraphId: '39F8fYCvLYmutjqpzEwx3dcEJTtFFVupvBzJqkEzftA7',
    schemaType: 'messari-rwa',
    website: 'https://truefi.io',
    chains: ['Ethereum'],
    color: '#5673E0',
  },
  {
    slug: 'stargate-arbitrum',
    name: 'Stargate (Arbitrum)',
    category: 'Bridge',
    description: 'Cross-chain liquidity transport built on LayerZero. Stargate routes native assets across chains via unified pools. This entry tracks the Arbitrum deployment, the highest-volume Stargate venue with $14B+ in lifetime bridge volume.',
    subgraphId: 'DWo7jrtpTtUM1buqiCUg7j7XUF568qNPBv7FwwDceuxm',
    schemaType: 'messari-bridge',
    website: 'https://stargate.finance',
    chains: ['Arbitrum'],
    color: '#3CC9F2',
  },
  {
    slug: 'stargate-optimism',
    name: 'Stargate (Optimism)',
    category: 'Bridge',
    description: 'Stargate cross-chain liquidity transport on Optimism. Routes native assets via unified pools. Second-largest Stargate venue by lifetime volume.',
    subgraphId: '7NAF7ZtNtJiXkfCFkTSAyFbfLLfUFa55UgK5woxPxZ46',
    schemaType: 'messari-bridge',
    website: 'https://stargate.finance',
    chains: ['Optimism'],
    color: '#FF0420',
  },
  {
    slug: 'cbridge',
    name: 'cBridge',
    category: 'Bridge',
    description: 'Celer Network multi-chain transport routing assets across 40+ chains. Ethereum deployment indexed here, with $10B+ in cumulative bridge volume.',
    subgraphId: 'DokJsCswtSfoQreapeZDaJR9jAfZ9t4zdNbNqgwM117L',
    schemaType: 'messari-bridge',
    website: 'https://cbridge.celer.network',
    chains: ['Ethereum'],
    color: '#5BC2F6',
  },
  {
    slug: 'arbitrum-one-bridge',
    name: 'Arbitrum One Bridge',
    category: 'Bridge',
    description: 'Canonical bridge between Ethereum mainnet and Arbitrum One. Custodies the bulk of bridged ETH, USDC, USDT, ARB, and other ERC-20s flowing into the largest L2 by TVL.',
    subgraphId: '6XazDBEjAVADSXbiBoXBBVwxTYf4PXRtucxn5vRQFLch',
    schemaType: 'messari-bridge',
    website: 'https://bridge.arbitrum.io',
    chains: ['Ethereum'],
    color: '#28A0F0',
  },
  {
    slug: 'optimism-bridge-v2',
    name: 'Optimism Bridge V2',
    category: 'Bridge',
    description: 'Canonical L1<->Optimism bridge. The official native deposit/withdrawal path; tracks bridged ETH, USDC, USDT, OP, and other ERC-20s held in the L1StandardBridge.',
    subgraphId: 'DCKLUdmvmaX4eNSAouXjxt8yShp28dFKGD763Tb2KibH',
    schemaType: 'messari-bridge',
    website: 'https://app.optimism.io/bridge',
    chains: ['Ethereum'],
    color: '#FF0420',
  },
  {
    slug: 'stargate-avalanche',
    name: 'Stargate (Avalanche)',
    category: 'Bridge',
    description: 'LayerZero-powered Stargate liquidity transport on Avalanche C-Chain. Routes USDC, USDT, ETH.e, and other assets to and from Stargate pools across chains.',
    subgraphId: '6XypMkQUovcohhVC2XeWgdXeDsBcnL9ynKdLXpXggoHd',
    schemaType: 'messari-bridge',
    website: 'https://stargate.finance',
    chains: ['Avalanche'],
    color: '#3CC9F2',
  },
  {
    slug: 'stargate-bsc',
    name: 'Stargate (BSC)',
    category: 'Bridge',
    description: 'Stargate liquidity transport on BNB Smart Chain. High-volume corridor for USDT, BUSD, and ETH bridging between BSC and other Stargate-enabled chains.',
    subgraphId: '6sRx6JNkjz66id39jCK3GMiVnPVuyuv2ntwQVpDzmjRF',
    schemaType: 'messari-bridge',
    website: 'https://stargate.finance',
    chains: ['BSC'],
    color: '#3CC9F2',
  },
  {
    slug: 'stargate-polygon',
    name: 'Stargate (Polygon)',
    category: 'Bridge',
    description: 'Stargate liquidity transport on Polygon PoS. Cross-chain pools for USDC, USDT, and bridged stablecoins between Polygon and the wider Stargate network.',
    subgraphId: 'SitmxEcPXXwo5cFK8Y2FSMZNZNQ4gXcGdWBDqo3A7K6',
    schemaType: 'messari-bridge',
    website: 'https://stargate.finance',
    chains: ['Polygon'],
    color: '#3CC9F2',
  },
  {
    slug: 'axelar',
    name: 'Axelar',
    category: 'Bridge',
    description: 'Cross-chain communication layer connecting 70+ chains via a proof-of-stake validator network. Ethereum deployment with $45M+ in pool TVL.',
    subgraphId: '8u1rrGZY3gjXAAVJidygbpKeHzitrMSQV1RoLAkyd1AA',
    schemaType: 'messari-bridge',
    website: 'https://axelar.network',
    chains: ['Ethereum'],
    color: '#FF6B57',
    knownIssues: 'The upstream subgraph reports $0 dailyTotalRevenueUSD across all snapshots while bridge volume is healthy. Daily fees chart shows no data until this is fixed upstream.',
    knownIssueAffects: 'fees',
  },
  {
    slug: 'polymarket',
    name: 'Polymarket',
    category: 'Prediction Markets',
    description: 'Largest decentralised prediction-market venue. CLOB-style orderbook on Polygon settling outcome shares against USDC collateral, with over a billion trades on $100B+ of lifetime notional.',
    // The Polymarket-team deployments are pinned by IPFS hash on the gateway,
    // not registered Subgraph IDs. The fetcher routes polymarket schemaType
    // queries to the deployment endpoint.
    subgraphId: 'QmVGA9vvNZtEquVzDpw8wnTFDxVjB6mavTRMTrKuUBhi4t',
    schemaType: 'polymarket',
    website: 'https://polymarket.com',
    chains: ['Polygon'],
    color: '#2D9CDB',
    knownIssues: 'Headline TVL is total cumulative open interest (USDC locked into outstanding outcome tokens) and includes residual "dead money" from resolved markets where losing-side tokens were never burned. 30d windows are not currently computed for Polymarket as the orderbook subgraph has no daily aggregate entity; the directory shows lifetime totals instead.',
  },
  {
    slug: 'kwenta',
    name: 'Kwenta',
    category: 'Perpetuals',
    description: 'Synthetix-powered perpetual futures DEX on Optimism. Settles trades against the Synthetix debt pool with deep synthetic-asset liquidity, no order book counterparties needed. Cumulative trade volume over $170B across BTC, ETH, SOL, and dozens of other perp markets.',
    subgraphId: '5sbJJTTJQQ4kYuVYNBVw9sX8C5juRpVJNLHg7uFugw2e',
    schemaType: 'messari-perp',
    website: 'https://kwenta.eth.limo',
    chains: ['Optimism'],
    color: '#ED1EFF',
  },
];

// Deployment IPFS hashes for Polymarket subgraphs that aren't registered as
// network Subgraphs but are exposed via the gateway's /deployments/id/ path.
// Maintained by the Polymarket team (per github.com/Polymarket/polymarket-subgraph
// and PaulieB14/graph-polymarket-mcp).
export const POLYMARKET_OI_DEPLOYMENT = 'QmbT2MmS2VGbGihiTUmWk6GMc2QYqoT9ZhiupUicYMWt6H';
export const POLYMARKET_MAIN_DEPLOYMENT = 'QmdyCguLEisTtQFveEkvMhTH7UzjyhnrF9kpvhYeG4QX8a';
export const POLYMARKET_RESOLUTION_DEPLOYMENT = 'QmZnnrHWCB1Mb8dxxXDxfComjNdaGyRC66W8derjn3XDPg';

export function getProtocol(slug: string): ProtocolConfig | undefined {
  return PROTOCOLS.find(p => p.slug === slug);
}
